export const REQUEST_REVIEWER_PENDING = 'REQUEST_REVIEWER_PENDING'

export const REQUEST_REVIEWER_SUCCESS = 'REQUEST_REVIEWER_SUCCESS'

export const REQUEST_REVIEWER_FAILED = 'REQUEST_REVIEWER_FAILED'

export const PREV_QUESTION = 'PREV_QUESTION'

export const NEXT_QUESTION = 'NEXT_QUESTION'

export const SKIP_QUESTION = 'SKIP_QUESTION'