export const REQUEST_REVIEWER_PENDING = 'REQUEST_REVIEWER_PENDING'

export const REQUEST_REVIEWER_SUCCESS = 'REQUEST_REVIEWER_SUCCESS'

export const REQUEST_REVIEWER_FAILED = 'REQUEST_REVIEWER_FAILED'